server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tasktracker
    username: postgres
    password: Lekshmi@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      indent_output: true
